# Generated by Django 2.2 on 2019-05-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190430_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingRequirements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('required_lvl', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='building', to='game.Building')),
                ('required_building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='required_building', to='game.Building')),
            ],
        ),
    ]
